### ISSUE TITLE
Invalid date remaining (games with no timer)

### ISSUE THREAD

**Issue by igorrafael** [quentinms/GMR-client#2]
Probably caused by my install using moment@2.15.1

> From version 2.10.3, if the target moment object is invalid the result is the localized Invalid date string. ([momentjs docs](http://momentjs.com/docs/#/displaying/fromnow/))

An easy fix would be restricting the version of moment on `package.js`. If you see that as a problem the logic [here](https://github.com/quentinms/GMR-client/blob/master/app/js/index.js#L122) could be changed as well.

edit: clarifying the source of the quote

**Comment by quentinms** [comment]
I think I'd rather change the logic (i.e check if `selectedGame.CurrentTurn.Expires` is valid before using moment) than locking ourself on a specific version, especially for such a small change.

If you want to open a PR for it, you're more than welcome. Otherwise I'll take care of it some time next week.
